# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
#    my.formation_file_uploader:
#        class: CoreBundle\Service\FormationFileUploader
#        arguments:
#            $_dir: '%formation_dir%'