<?php

namespace CoreBundle\Repository;

/**
 * AcountRepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcountRepRepository extends \Doctrine\ORM\EntityRepository
{
}
