<?php

namespace CoreBundle\Repository;

/**
 * ComptePercevableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptePercevableRepository extends \Doctrine\ORM\EntityRepository
{
}
