<?php

namespace CoreBundle\Repository;

/**
 * CompteAlimentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteAlimentationRepository extends \Doctrine\ORM\EntityRepository
{
}
