<?php

namespace CoreBundle\Repository;

/**
 * CptPerGainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CptPerGainRepository extends \Doctrine\ORM\EntityRepository
{
}
