<?php

namespace CoreBundle\Repository;

/**
 * DemandeDeRetraitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeDeRetraitRepository extends \Doctrine\ORM\EntityRepository
{
}
