<?php

namespace CoreBundle\Repository;

/**
 * DescendantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescendantRepository extends \Doctrine\ORM\EntityRepository
{
}
