<?php

namespace CoreBundle\Repository;

/**
 * FormationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
