<?php

namespace CoreBundle\Repository;

/**
 * FormationUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationUserRepository extends \Doctrine\ORM\EntityRepository
{
}
