<?php

namespace CoreBundle\Repository;

/**
 * UserProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
