<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserMatriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMatriceRepository extends EntityRepository
{
}